<?php
/**
 * @file
 * Module file for circles.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_node_access().
 */
function circles_node_access(NodeInterface $node, $op, AccountInterface $account, $langcode) {
  switch ($op) {
    case 'view':
      if (\Drupal::service('circles')->canView($account, $node)) {
        return NODE_ACCESS_ALLOW;
      }
      break;

    case 'create':
      break;

    case 'delete':
      break;

    case 'update':
      break;
  }

  // @todo Return NODE_ACCESS_IGNORE if the content is "public".

  return NODE_ACCESS_DENY;
}

/**
 * Implements hook_entity_access().
 */
function circles_entity_access(EntityInterface $entity, $operation, AccountInterface $account, $langcode) {

}
